import './globals.css'
import { Providers } from "./redux/providers";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <div className="container mx-auto bg-red-100">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  )
}
